# Generated by Django 5.1 on 2024-09-18 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('formed_date', models.DateField()),
                ('members', models.ManyToManyField(related_name='bands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
